//=============================================================================
//
// file :         PSI_PCClass.h
//
// description :  Include for the PSI_PCClass root class.
//                This class is represents the singleton class for
//                the PSI_PC device class.
//                It contains all properties and methods which the 
//                PSI_PC requires only once e.g. the commands.
//                      
// project :      TANGO Device Server
//
// $Author:  $
//
// $Revision:  $
//
// $Log:  $
//
// copyleft :     European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                FRANCE
//
//=============================================================================
//
//              This file is generated by POGO
//      (Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#ifndef _PSI_PCCLASS_H
#define _PSI_PCCLASS_H

#include <tango.h>
#include <PSI_PC.h>


namespace PSI_PC_ns
{//=====================================
//	Define classes for attributes
//=====================================
class ErrorsAttrib: public Tango::SpectrumAttr
{
public:
	ErrorsAttrib():SpectrumAttr("Errors", Tango::DEV_STRING, Tango::READ, 20) {};
	~ErrorsAttrib() {};
	
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
	{(static_cast<PSI_PC *>(dev))->read_Errors(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
	{return (static_cast<PSI_PC *>(dev))->is_Errors_allowed(ty);}
};

class ErrorLabelAttrib: public Tango::SpectrumAttr
{
public:
	ErrorLabelAttrib():SpectrumAttr("ErrorLabel", Tango::DEV_STRING, Tango::READ, 5) {};
	~ErrorLabelAttrib() {};
	
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
	{(static_cast<PSI_PC *>(dev))->read_ErrorLabel(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
	{return (static_cast<PSI_PC *>(dev))->is_ErrorLabel_allowed(ty);}
};

class ErrorCodesAttrib: public Tango::SpectrumAttr
{
public:
	ErrorCodesAttrib():SpectrumAttr("ErrorCodes", Tango::DEV_SHORT, Tango::READ, 5) {};
	~ErrorCodesAttrib() {};
	
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
	{(static_cast<PSI_PC *>(dev))->read_ErrorCodes(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
	{return (static_cast<PSI_PC *>(dev))->is_ErrorCodes_allowed(ty);}
};

class SoftwareWaveformAttrib: public Tango::SpectrumAttr
{
public:
	SoftwareWaveformAttrib():SpectrumAttr("SoftwareWaveform", Tango::DEV_DOUBLE, Tango::READ_WRITE, 1000000) {};
	~SoftwareWaveformAttrib() {};
	
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
	{(static_cast<PSI_PC *>(dev))->read_SoftwareWaveform(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
	{(static_cast<PSI_PC *>(dev))->write_SoftwareWaveform(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
	{return (static_cast<PSI_PC *>(dev))->is_SoftwareWaveform_allowed(ty);}
};

class IAttrib: public Tango::Attr
{
public:
	IAttrib():Attr("I", Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~IAttrib() {};
	
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
	{(static_cast<PSI_PC *>(dev))->read_I(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
	{(static_cast<PSI_PC *>(dev))->write_I(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
	{return (static_cast<PSI_PC *>(dev))->is_I_allowed(ty);}
};

class CurrentOffsetAttrib: public Tango::Attr
{
public:
	CurrentOffsetAttrib():Attr("CurrentOffset", Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~CurrentOffsetAttrib() {};
	
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
	{(static_cast<PSI_PC *>(dev))->read_CurrentOffset(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
	{(static_cast<PSI_PC *>(dev))->write_CurrentOffset(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
	{return (static_cast<PSI_PC *>(dev))->is_CurrentOffset_allowed(ty);}
};

class CurrentAttrib: public Tango::Attr
{
public:
	CurrentAttrib():Attr("Current", Tango::DEV_DOUBLE, Tango::READ) {};
	~CurrentAttrib() {};
	
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
	{(static_cast<PSI_PC *>(dev))->read_Current(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
	{return (static_cast<PSI_PC *>(dev))->is_Current_allowed(ty);}
};

class RemoteModeAttrib: public Tango::Attr
{
public:
	RemoteModeAttrib():Attr("RemoteMode", Tango::DEV_BOOLEAN, Tango::READ) {};
	~RemoteModeAttrib() {};
	
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
	{(static_cast<PSI_PC *>(dev))->read_RemoteMode(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
	{return (static_cast<PSI_PC *>(dev))->is_RemoteMode_allowed(ty);}
};

class VoltageAttrib: public Tango::Attr
{
public:
	VoltageAttrib():Attr("Voltage", Tango::DEV_DOUBLE, Tango::READ) {};
	~VoltageAttrib() {};
	
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
	{(static_cast<PSI_PC *>(dev))->read_Voltage(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
	{return (static_cast<PSI_PC *>(dev))->is_Voltage_allowed(ty);}
};

class CurrentSetpointAttrib: public Tango::Attr
{
public:
	CurrentSetpointAttrib():Attr("CurrentSetpoint", Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~CurrentSetpointAttrib() {};
	
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
	{(static_cast<PSI_PC *>(dev))->read_CurrentSetpoint(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
	{(static_cast<PSI_PC *>(dev))->write_CurrentSetpoint(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
	{return (static_cast<PSI_PC *>(dev))->is_CurrentSetpoint_allowed(ty);}
};

//=========================================
//	Define classes for commands
//=========================================
class UpdateCmd : public Tango::Command
{
public:
	UpdateCmd(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	UpdateCmd(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~UpdateCmd() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<PSI_PC *>(dev))->is_Update_allowed(any);}
};



class ConnectCmd : public Tango::Command
{
public:
	ConnectCmd(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	ConnectCmd(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~ConnectCmd() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<PSI_PC *>(dev))->is_Connect_allowed(any);}
};



class StartSoftwareWaveformClass : public Tango::Command
{
public:
	StartSoftwareWaveformClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	StartSoftwareWaveformClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~StartSoftwareWaveformClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<PSI_PC *>(dev))->is_StartSoftwareWaveform_allowed(any);}
};



class StopSoftwareWaveformClass : public Tango::Command
{
public:
	StopSoftwareWaveformClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	StopSoftwareWaveformClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~StopSoftwareWaveformClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<PSI_PC *>(dev))->is_StopSoftwareWaveform_allowed(any);}
};



class Read_PSC_registerCmd : public Tango::Command
{
public:
	Read_PSC_registerCmd(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	Read_PSC_registerCmd(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~Read_PSC_registerCmd() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<PSI_PC *>(dev))->is_Read_PSC_register_allowed(any);}
};



class InterlockStatusCmd : public Tango::Command
{
public:
	InterlockStatusCmd(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	InterlockStatusCmd(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~InterlockStatusCmd() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<PSI_PC *>(dev))->is_InterlockStatus_allowed(any);}
};



class EnableInterlocksCmd : public Tango::Command
{
public:
	EnableInterlocksCmd(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	EnableInterlocksCmd(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~EnableInterlocksCmd() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<PSI_PC *>(dev))->is_EnableInterlocks_allowed(any);}
};



class DisableInterlocksCmd : public Tango::Command
{
public:
	DisableInterlocksCmd(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	DisableInterlocksCmd(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~DisableInterlocksCmd() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<PSI_PC *>(dev))->is_DisableInterlocks_allowed(any);}
};



class ResetInterlocksCmd : public Tango::Command
{
public:
	ResetInterlocksCmd(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	ResetInterlocksCmd(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~ResetInterlocksCmd() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<PSI_PC *>(dev))->is_ResetInterlocks_allowed(any);}
};



class ResetClass : public Tango::Command
{
public:
	ResetClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	ResetClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~ResetClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<PSI_PC *>(dev))->is_Reset_allowed(any);}
};



class OffClass : public Tango::Command
{
public:
	OffClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	OffClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~OffClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<PSI_PC *>(dev))->is_Off_allowed(any);}
};



class OnClass : public Tango::Command
{
public:
	OnClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	OnClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~OnClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<PSI_PC *>(dev))->is_On_allowed(any);}
};



//
// The PSI_PCClass singleton definition
//

class
#ifdef WIN32
	__declspec(dllexport)
#endif
	PSI_PCClass : public Tango::DeviceClass
{
public:
//	properties member data
/**
 *	
 */
	string	interlock1;
/**
 *	message to be shown for external interlock 2
 */
	string	interlock2;

//	add your own data members here
//------------------------------------

public:
	Tango::DbData	cl_prop;
	Tango::DbData	cl_def_prop;
	Tango::DbData	dev_def_prop;

//	Method prototypes
	static PSI_PCClass *init(const char *);
	static PSI_PCClass *instance();
	~PSI_PCClass();
	Tango::DbDatum	get_class_property(string &);
	Tango::DbDatum	get_default_device_property(string &);
	Tango::DbDatum	get_default_class_property(string &);
	
protected:
	PSI_PCClass(string &);
	static PSI_PCClass *_instance;
	void command_factory();
	void get_class_property();
	void attribute_factory(vector<Tango::Attr *> &);
	void write_class_property();
	void set_default_property();
	string get_cvstag();
	string get_cvsroot();

private:
	void device_factory(const Tango::DevVarStringArray *);
};


}	//	namespace PSI_PC_ns

#endif // _PSI_PCCLASS_H
