Z:/Project/development/PSCIP/driver/debug_pscip.c File Reference
Z:/Project/development/PSCIP/driver/debug_pscip.c File Reference
Includes functions used while debugging.
Functions
void IP_DEBUG_read_FPGA_stat (volatile struct FPGAstatus_reg *pReg)
void IP_DEBUG_read_IP_interface_reg (volatile struct IPLocalSpace0 *pReg)
int IP_DEBUG_read_errors (pscip_Dev dev)
static unsigned char pscip_get_PCI_info (struct pci_dev *dev)
Detailed Description
Includes functions used while debugging.
This functions interprete IP and PCI Carrier registers - make life much easier for the developer
Definition in file debug_pscip.c.
Function Documentation
int IP_DEBUG_read_errors (pscip_Dev dev)
Definition at line 280 of file debug_pscip.c.
References pscip_fpga_t::channel, pscip_stats_t::cntrl_stat, pscip_fpga_t::high_data, npscip_Dev::IPnumber, k_pscip_rdfpgastat(), pscip_stats_t::linkdown_cnt, PSCIP_DSP_MSK, PSCIP_INPUTBUF_MSK, PSCIP_LINKDOWN_MSK, PSCIP_REMLOC_MSK, PSCIP_TXERR_MSK, pscip_stats_t::rx, npscip_Dev::stats, pscip_stats_t::tx, and pscip_stats_t::txerr_cnt.
void IP_DEBUG_read_FPGA_stat (volatile struct FPGAstatus_reg * pReg)
Definition at line 6 of file debug_pscip.c.
References FPGAstatus_reg::errorCounter, FPGAstatus_reg::highWord, FPGAstatus_reg::lowWord, FPGAstatus_reg::midWord, PSCIP_BREAK_ERR_0_MSK, PSCIP_BREAK_ERR_1_MSK, PSCIP_BREAK_ERR_2_MSK, PSCIP_BREAK_ERR_3_MSK, PSCIP_BREAK_ERR_4_MSK, PSCIP_COMP_ERR_0_MSK, PSCIP_COMP_ERR_1_MSK, PSCIP_COMP_ERR_2_MSK, PSCIP_COMP_ERR_3_MSK, PSCIP_COMP_ERR_4_MSK, PSCIP_FRAME_ERR_0_MSK, PSCIP_FRAME_ERR_1_MSK, PSCIP_FRAME_ERR_2_MSK, PSCIP_FRAME_ERR_3_MSK, PSCIP_FRAME_ERR_4_MSK, PSCIP_LINKDOWN_MSK, PSCIP_LOOPBACK_MSK, PSCIP_PAR_ERR_0_MSK, PSCIP_PAR_ERR_1_MSK, PSCIP_PAR_ERR_2_MSK, PSCIP_PAR_ERR_3_MSK, PSCIP_PAR_ERR_4_MSK, PSCIP_TIMEOUT_ERR_0_MSK, PSCIP_TIMEOUT_ERR_1_MSK, PSCIP_TIMEOUT_ERR_2_MSK, PSCIP_TIMEOUT_ERR_3_MSK, PSCIP_TIMEOUT_ERR_4_MSK, and PSCIP_TXERR_MSK.
Referenced by pscip_ioctl().
void IP_DEBUG_read_IP_interface_reg (volatile struct IPLocalSpace0 * pReg)
Definition at line 149 of file debug_pscip.c.
References IP_CLKRATE, IP_ERR_A, IP_ERR_B, IP_ERR_INT_EN, IP_INT0_A, IP_INT0_B, IP_INT0_EN, IP_INT0_SENSE, IP_INT1_A, IP_INT1_B, IP_INT1_EN, IP_INT1_SENSE, IP_RECOVER, IP_TIME_A, IP_TIME_B, IPA_RESET_MASK, IPLocalSpace0::IPAcontrol, IPB_RESET_MASK, IPLocalSpace0::IPBcontrol, IPLocalSpace0::RESET, IPLocalSpace0::revisionID, and IPLocalSpace0::STATUS.
Referenced by pscip_ioctl().
static unsigned char pscip_get_PCI_info (struct pci_dev * dev) [static]
Definition at line 339 of file debug_pscip.c.
Referenced by probe().