Z:/Project/development/PSCIP/driver/k_pscip.h File Reference
Z:/Project/development/PSCIP/driver/k_pscip.h File Reference
Defines interface with kernel, device structure, IP addresses and masks.
Data Structures
struct npscip_Dev
Structure to mantain internal device driver variables.
struct Pci9030LocalConf
struct npscip_Proc
Defines
#define PSCIP_SIZE 0x100
#define PSCIP_HPRIOWRITE_REG 0x0
#define PSCIP_HPRIOWRITE_STAT 0x1
#define PSCIP_HPRIOWRITE_ADDR 0x0
#define PSCIP_HPRIOWRITE_DATA 0x2
#define PSCIP_WRITE_REG 0x8
#define PSCIP_WRITE_STAT 0x9
#define PSCIP_WRITE_ADDR 0x8
#define PSCIP_WRITE_DATA 0xa
#define PSCIP_READ_REG 0x10
#define PSCIP_READ_STAT 0x11
#define PSCIP_READ_ADDR 0x10
#define PSCIP_READ_DATA 0x12
#define PSCIP_WRWAVE_REG 0x18
#define PSCIP_WRWAVE_STAT 0x19
#define PSCIP_WRWAVE_ADDR 0x18
#define PSCIP_WRWAVE_DATA 0x1a
#define PSCIP_RDWAVE_REG 0x20
#define PSCIP_RDWAVE_STAT 0x20
#define PSCIP_RDWAVE_ADDR 0x21
#define PSCIP_RDWAVE_DATA 0x22
#define PSCIP_BRK_REG 0x28
#define PSCIP_BRK_STAT 0x28
#define PSCIP_BRK_ADDR 0x29
#define PSCIP_BRK_DATA 0x2a
#define PSCIP_FPGA_REG 0x30
#define PSCIP_FPGA_HIGH 0x30
#define PSCIP_FPGA_MID 0x32
#define PSCIP_FPGA_LOW 0x34
#define PSCIP_REG_STAT 0x38
#define PSCIP_IVEC_REG 0x3A
#define PSCIP_PROM_OFFSET 0x80 - 0x01
#define PSCIP_MODEL_REG 0xB + PSCIP_PROM_OFFSET
#define PSCIP_MANIFAC_REG 0x9 + PSCIP_PROM_OFFSET
#define PSCIP_ILEV_REG 0xC1
#define PSCIP_RESET_REG 0xC3
#define PSCIP_MANIFAC_ID 0xB
#define PSCIP_MODEL_ID 0x1B
#define PSCIP_RESET_MASK 0x80
#define PSCIP_PROC_HPRIO 1
#define PSCIP_PROC_WRITE 2
#define PSCIP_PROC_WRWAVE 3
#define PSCIP_PROC_RESET 100
#define PSCIP_IRQ_REQUEST 2
#define PSCIP_IRQ_SERVED 1
#define PSCIP_IRQ_DONE 0
#define PSCIP_MAX_DEV 20
#define PSCIP_DEFAULT_DEV 8
#define MAX_NUMER_OF_IPs_ON_CARRIER 2
#define PSCIP_CHAN_OFFSET 0x40
#define PSCIP_IP_OFFSET 0x100
#define PSCIP_BUSY_TOUT 150000
#define PSCIP_MAX_READ 100
#define PSCIP_MAX_CHAN 2
#define PCI_VENDOR_ID_TEWS 0x1498
#define PCI_DEVICE_ID_TCP221_cPCI 0x20D3
#define PCI_DEVICE_ID_TCPI100_PCI 0x3064
#define IP_REVISION_ID 0x00
#define IP_A_CONTROL 0x02
#define IP_B_CONTROL 0x04
#define IP_RESET 0x0A
#define IP_STATUS 0x0C
#define IP_INT1_EN 0x0080
#define IP_INT0_EN 0x0040
#define IP_INT1_SENSE 0x0020
#define IP_INT0_SENSE 0x0010
#define IP_ERR_INT_EN 0x0008
#define IP_TIME_INT_EN 0x0004
#define IP_RECOVER 0x0002
#define IP_CLKRATE 0x0001
#define IPB_RESET_MASK 0x0002
#define IPA_RESET_MASK 0x0001
#define IP_TIME_B 0x2000
#define IP_TIME_A 0x1000
#define IP_ERR_B 0x0200
#define IP_ERR_A 0x0100
#define IP_INT1_B 0x0008
#define IP_INT0_B 0x0004
#define IP_INT1_A 0x0002
#define IP_INT0_A 0x0001
#define IP_A_IO_SPACE 0x00000000
#define IP_A_ID_SPACE 0x00000080
#define IP_A_INT_SPACE 0x000000C0
#define IP_B_IO_SPACE 0x00000100
#define IP_B_ID_SPACE 0x00000180
#define IP_B_INT_SPACE 0x000001C0
#define IP_INT0_ACK 0x000000C0
#define IP_INT1_ACK 0x000000C2
#define PLX9030_INTCSR_LINTI1_ENA 0x0001
#define PLX9030_INTCSR_LINTI1_POL 0x0002
#define PLX9030_INTCSR_LINTI1_STAT 0x0004
#define PLX9030_INTCSR_LINTI2_ENA 0x0008
#define PLX9030_INTCSR_LINTI2_POL 0x0010
#define PLX9030_INTCSR_LINTI2_STAT 0x0020
#define PLX9030_INTCSR_PCI_IRQENA 0x0040
#define PLX9030_INTCSR_SWINT 0x0080
#define PLX9030_INTCSR_LINTI1_SENA 0x0100
#define PLX9030_INTCSR_LINTI2_SENA 0x0200
#define PLX9030_INTCSR_LINTI1_ICLR 0x0400
#define PLX9030_INTCSR_LINTI2_ICLR 0x0800
#define FALSE 0
#define TRUE 1
Typedefs
typedef struct npscip_Dev * pscip_Dev
typedef struct npscip_Proc * pscip_Proc
Functions
int k_pscip_wait_linkdown (pscip_t *, int, pscip_Dev)
Wait after linkdown.
int k_pscip_wrhiprio (pscip_t *, int, pscip_Dev)
Execute high priority PS-current setting.
int k_pscip_write (pscip_t *, int, pscip_Dev)
Execute writing action.
int k_pscip_read (pscip_t *, int, pscip_Dev)
Execute reading action.
int k_pscip_wrwave (pscip_t *, int, pscip_Dev)
Write wave value.
int k_pscip_rdwave (pscip_t *, int, pscip_Dev)
Execute reading action Function reads data (2 words) of a waveform from given address in PS.
int k_pscip_wrstat (pscip_t *, int, pscip_Dev)
int k_pscip_rdlinkstat (pscip_t *, int, pscip_Dev)
Read link status.
int k_pscip_rdfpgastat (pscip_fpga_t *, int, pscip_Dev)
Read FPGA status register FPGA status register is for debugging purposes and reflects the error status of the FPGA.
int k_pscip_rdstatistics (pscip_stats_t *, int, pscip_Dev)
Read transmission statistics.
int k_pscip_reset (int, pscip_Dev)
Reset IP.
int k_pscip_clear_err_counter (pscip_t *val, int id_pscip, pscip_Dev dev)
Clean error counter in FPGA status register.
int k_pscip_dump_all_registers (pscip_t *val, int id_pscip, pscip_Dev dev)
Dumps content of all the registers of both IPs on the carrier and of Local Space O (BADR 2) on the Carrier.
void IP_read_byte (void *address, uint8_t *val)
Reads byte from the device.
void IP_read_word (void *address, uint16_t *val)
Reads word from the device.
void IP_write_byte (void *address, uint8_t val)
Writing byte to the device.
void IP_write_word (void *address, uint16_t val)
Writing word to the device.
Detailed Description
Defines interface with kernel, device structure, IP addresses and masks.
GG - 18.07.2005: First implementation
22/10/2008 - Start of porting the driver :
from 2.4.x to 2.6.x
from VME to PCIGG
Definition in file k_pscip.h.
Define Documentation
#define FALSE 0
Definition at line 175 of file k_pscip.h.
Referenced by init_pscip_module(), and probe().
#define IP_A_CONTROL 0x02
Definition at line 119 of file k_pscip.h.
Referenced by k_irq_disable(), and k_irq_enable().
#define IP_A_ID_SPACE 0x00000080
Definition at line 151 of file k_pscip.h.
#define IP_A_INT_SPACE 0x000000C0
Definition at line 152 of file k_pscip.h.
#define IP_A_IO_SPACE 0x00000000
Definition at line 150 of file k_pscip.h.
#define IP_B_CONTROL 0x04
Definition at line 120 of file k_pscip.h.
Referenced by k_irq_disable(), and k_irq_enable().
#define IP_B_ID_SPACE 0x00000180
Definition at line 155 of file k_pscip.h.
#define IP_B_INT_SPACE 0x000001C0
Definition at line 156 of file k_pscip.h.
#define IP_B_IO_SPACE 0x00000100
Definition at line 154 of file k_pscip.h.
#define IP_CLKRATE 0x0001
Definition at line 133 of file k_pscip.h.
Referenced by IP_DEBUG_read_IP_interface_reg().
#define IP_ERR_A 0x0100
Definition at line 143 of file k_pscip.h.
Referenced by IP_DEBUG_read_IP_interface_reg().
#define IP_ERR_B 0x0200
Definition at line 142 of file k_pscip.h.
Referenced by IP_DEBUG_read_IP_interface_reg().
#define IP_ERR_INT_EN 0x0008
Definition at line 130 of file k_pscip.h.
Referenced by IP_DEBUG_read_IP_interface_reg().
#define IP_INT0_A 0x0001
Definition at line 147 of file k_pscip.h.
Referenced by IP_DEBUG_read_IP_interface_reg(), and k_if_handle_irq().
#define IP_INT0_ACK 0x000000C0
Definition at line 157 of file k_pscip.h.
#define IP_INT0_B 0x0004
Definition at line 145 of file k_pscip.h.
Referenced by IP_DEBUG_read_IP_interface_reg(), and k_if_handle_irq().
#define IP_INT0_EN 0x0040
Definition at line 127 of file k_pscip.h.
Referenced by IP_DEBUG_read_IP_interface_reg(), and k_irq_enable().
#define IP_INT0_SENSE 0x0010
Definition at line 129 of file k_pscip.h.
Referenced by IP_DEBUG_read_IP_interface_reg().
#define IP_INT1_A 0x0002
Definition at line 146 of file k_pscip.h.
Referenced by IP_DEBUG_read_IP_interface_reg(), and k_if_handle_irq().
#define IP_INT1_ACK 0x000000C2
Definition at line 158 of file k_pscip.h.
#define IP_INT1_B 0x0008
Definition at line 144 of file k_pscip.h.
Referenced by IP_DEBUG_read_IP_interface_reg(), and k_if_handle_irq().
#define IP_INT1_EN 0x0080
Definition at line 126 of file k_pscip.h.
Referenced by IP_DEBUG_read_IP_interface_reg(), and k_irq_enable().
#define IP_INT1_SENSE 0x0020
Definition at line 128 of file k_pscip.h.
Referenced by IP_DEBUG_read_IP_interface_reg().
#define IP_RECOVER 0x0002
Definition at line 132 of file k_pscip.h.
Referenced by IP_DEBUG_read_IP_interface_reg().
#define IP_RESET 0x0A
Definition at line 121 of file k_pscip.h.
Referenced by k_pscip_reset().
#define IP_REVISION_ID 0x00
Definition at line 118 of file k_pscip.h.
#define IP_STATUS 0x0C
Definition at line 122 of file k_pscip.h.
Referenced by k_if_handle_irq().
#define IP_TIME_A 0x1000
Definition at line 141 of file k_pscip.h.
Referenced by IP_DEBUG_read_IP_interface_reg().
#define IP_TIME_B 0x2000
Definition at line 140 of file k_pscip.h.
Referenced by IP_DEBUG_read_IP_interface_reg().
#define IP_TIME_INT_EN 0x0004
Definition at line 131 of file k_pscip.h.
#define IPA_RESET_MASK 0x0001
Definition at line 137 of file k_pscip.h.
Referenced by IP_DEBUG_read_IP_interface_reg().
#define IPB_RESET_MASK 0x0002
Definition at line 136 of file k_pscip.h.
Referenced by IP_DEBUG_read_IP_interface_reg().
#define MAX_NUMER_OF_IPs_ON_CARRIER 2
Definition at line 93 of file k_pscip.h.
Referenced by probe().
#define PCI_DEVICE_ID_TCP221_cPCI 0x20D3
Definition at line 113 of file k_pscip.h.
#define PCI_DEVICE_ID_TCPI100_PCI 0x3064
Definition at line 114 of file k_pscip.h.
#define PCI_VENDOR_ID_TEWS 0x1498
Definition at line 112 of file k_pscip.h.
#define PLX9030_INTCSR_LINTI1_ENA 0x0001
Definition at line 162 of file k_pscip.h.
#define PLX9030_INTCSR_LINTI1_ICLR 0x0400
Definition at line 172 of file k_pscip.h.
#define PLX9030_INTCSR_LINTI1_POL 0x0002
Definition at line 163 of file k_pscip.h.
#define PLX9030_INTCSR_LINTI1_SENA 0x0100
Definition at line 170 of file k_pscip.h.
#define PLX9030_INTCSR_LINTI1_STAT 0x0004
Definition at line 164 of file k_pscip.h.
Referenced by pscip_irq_handler().
#define PLX9030_INTCSR_LINTI2_ENA 0x0008
Definition at line 165 of file k_pscip.h.
#define PLX9030_INTCSR_LINTI2_ICLR 0x0800
Definition at line 173 of file k_pscip.h.
#define PLX9030_INTCSR_LINTI2_POL 0x0010
Definition at line 166 of file k_pscip.h.
#define PLX9030_INTCSR_LINTI2_SENA 0x0200
Definition at line 171 of file k_pscip.h.
#define PLX9030_INTCSR_LINTI2_STAT 0x0020
Definition at line 167 of file k_pscip.h.
#define PLX9030_INTCSR_PCI_IRQENA 0x0040
Definition at line 168 of file k_pscip.h.
#define PLX9030_INTCSR_SWINT 0x0080
Definition at line 169 of file k_pscip.h.
#define PSCIP_BRK_ADDR 0x29
Definition at line 49 of file k_pscip.h.
#define PSCIP_BRK_DATA 0x2a
Definition at line 50 of file k_pscip.h.
#define PSCIP_BRK_REG 0x28
Definition at line 47 of file k_pscip.h.
#define PSCIP_BRK_STAT 0x28
Definition at line 48 of file k_pscip.h.
#define PSCIP_BUSY_TOUT 150000
Definition at line 102 of file k_pscip.h.
Referenced by k_pscip_rdwave(), k_pscip_read(), k_pscip_wrhiprio(), k_pscip_write(), and k_pscip_wrwave().
#define PSCIP_CHAN_OFFSET 0x40
Definition at line 99 of file k_pscip.h.
Referenced by k_pscip_dump_all_registers(), and probe().
#define PSCIP_DEFAULT_DEV 8
Definition at line 92 of file k_pscip.h.
Referenced by init_pscip_module().
#define PSCIP_FPGA_HIGH 0x30
Definition at line 53 of file k_pscip.h.
Referenced by k_pscip_clear_err_counter(), k_pscip_rdfpgastat(), k_pscip_wait_linkdown(), and pscip_irq_handler().
#define PSCIP_FPGA_LOW 0x34
Definition at line 55 of file k_pscip.h.
Referenced by k_pscip_clear_err_counter(), k_pscip_rdfpgastat(), k_pscip_wait_linkdown(), and pscip_irq_handler().
#define PSCIP_FPGA_MID 0x32
Definition at line 54 of file k_pscip.h.
Referenced by k_pscip_rdfpgastat(), and pscip_irq_handler().
#define PSCIP_FPGA_REG 0x30
Definition at line 52 of file k_pscip.h.
Referenced by pscip_ioctl().
#define PSCIP_HPRIOWRITE_ADDR 0x0
Definition at line 24 of file k_pscip.h.
#define PSCIP_HPRIOWRITE_DATA 0x2
Definition at line 25 of file k_pscip.h.
Referenced by k_pscip_wrhiprio().
#define PSCIP_HPRIOWRITE_REG 0x0
Definition at line 22 of file k_pscip.h.
Referenced by k_pscip_wrhiprio().
#define PSCIP_HPRIOWRITE_STAT 0x1
Definition at line 23 of file k_pscip.h.
Referenced by k_pscip_rdlinkstat(), and k_pscip_wrhiprio().
#define PSCIP_ILEV_REG 0xC1
Definition at line 68 of file k_pscip.h.
#define PSCIP_IP_OFFSET 0x100
Definition at line 100 of file k_pscip.h.
Referenced by k_pscip_dump_all_registers(), and probe().
#define PSCIP_IRQ_DONE 0
Definition at line 88 of file k_pscip.h.
Referenced by k_pscip_rdwave(), k_pscip_read(), k_pscip_wrhiprio(), k_pscip_write(), and k_pscip_wrwave().
#define PSCIP_IRQ_REQUEST 2
Definition at line 86 of file k_pscip.h.
Referenced by k_pscip_rdwave(), k_pscip_read(), k_pscip_wrhiprio(), k_pscip_write(), and k_pscip_wrwave().
#define PSCIP_IRQ_SERVED 1
Definition at line 87 of file k_pscip.h.
Referenced by k_pscip_rdwave(), k_pscip_read(), k_pscip_wrhiprio(), k_pscip_write(), k_pscip_wrwave(), and pscip_irq_handler().
#define PSCIP_IVEC_REG 0x3A
Definition at line 59 of file k_pscip.h.
#define PSCIP_MANIFAC_ID 0xB
Definition at line 70 of file k_pscip.h.
Referenced by checkmem_device().
#define PSCIP_MANIFAC_REG 0x9 + PSCIP_PROM_OFFSET
Definition at line 67 of file k_pscip.h.
Referenced by checkmem_device().
#define PSCIP_MAX_CHAN 2
Definition at line 109 of file k_pscip.h.
Referenced by init_pscip_module(), and pscip_read_proc().
#define PSCIP_MAX_DEV 20
Definition at line 91 of file k_pscip.h.
Referenced by init_pscip_module().
#define PSCIP_MAX_READ 100
Definition at line 106 of file k_pscip.h.
#define PSCIP_MODEL_ID 0x1B
Definition at line 71 of file k_pscip.h.
Referenced by checkmem_device().
#define PSCIP_MODEL_REG 0xB + PSCIP_PROM_OFFSET
Definition at line 66 of file k_pscip.h.
Referenced by checkmem_device().
#define PSCIP_PROC_HPRIO 1
Definition at line 77 of file k_pscip.h.
Referenced by pscip_write_proc().
#define PSCIP_PROC_RESET 100
Definition at line 80 of file k_pscip.h.
Referenced by pscip_write_proc().
#define PSCIP_PROC_WRITE 2
Definition at line 78 of file k_pscip.h.
Referenced by pscip_write_proc().
#define PSCIP_PROC_WRWAVE 3
Definition at line 79 of file k_pscip.h.
Referenced by pscip_write_proc().
#define PSCIP_PROM_OFFSET 0x80 - 0x01
Definition at line 65 of file k_pscip.h.
#define PSCIP_RDWAVE_ADDR 0x21
Definition at line 44 of file k_pscip.h.
#define PSCIP_RDWAVE_DATA 0x22
Definition at line 45 of file k_pscip.h.
Referenced by k_pscip_rdwave().
#define PSCIP_RDWAVE_REG 0x20
Definition at line 42 of file k_pscip.h.
Referenced by k_pscip_rdwave().
#define PSCIP_RDWAVE_STAT 0x20
Definition at line 43 of file k_pscip.h.
Referenced by k_pscip_rdlinkstat(), and k_pscip_rdwave().
#define PSCIP_READ_ADDR 0x10
Definition at line 34 of file k_pscip.h.
Referenced by k_pscip_read().
#define PSCIP_READ_DATA 0x12
Definition at line 35 of file k_pscip.h.
Referenced by k_pscip_read().
#define PSCIP_READ_REG 0x10
Definition at line 32 of file k_pscip.h.
Referenced by k_pscip_read().
#define PSCIP_READ_STAT 0x11
Definition at line 33 of file k_pscip.h.
Referenced by k_pscip_rdlinkstat(), and k_pscip_read().
#define PSCIP_REG_STAT 0x38
Definition at line 57 of file k_pscip.h.
Referenced by pscip_irq_handler().
#define PSCIP_RESET_MASK 0x80
Definition at line 72 of file k_pscip.h.
#define PSCIP_RESET_REG 0xC3
Definition at line 69 of file k_pscip.h.
#define PSCIP_SIZE 0x100
Definition at line 16 of file k_pscip.h.
#define PSCIP_WRITE_ADDR 0x8
Definition at line 29 of file k_pscip.h.
#define PSCIP_WRITE_DATA 0xa
Definition at line 30 of file k_pscip.h.
Referenced by k_pscip_write().
#define PSCIP_WRITE_REG 0x8
Definition at line 27 of file k_pscip.h.
Referenced by k_pscip_write().
#define PSCIP_WRITE_STAT 0x9
Definition at line 28 of file k_pscip.h.
Referenced by k_pscip_rdlinkstat(), and k_pscip_write().
#define PSCIP_WRWAVE_ADDR 0x18
Definition at line 39 of file k_pscip.h.
#define PSCIP_WRWAVE_DATA 0x1a
Definition at line 40 of file k_pscip.h.
Referenced by k_pscip_wrwave().
#define PSCIP_WRWAVE_REG 0x18
Definition at line 37 of file k_pscip.h.
Referenced by k_pscip_wrwave().
#define PSCIP_WRWAVE_STAT 0x19
Definition at line 38 of file k_pscip.h.
Referenced by k_pscip_rdlinkstat(), and k_pscip_wrwave().
#define TRUE 1
Definition at line 176 of file k_pscip.h.
Referenced by probe().
Typedef Documentation
typedef struct npscip_Dev * pscip_Dev
typedef struct npscip_Proc * pscip_Proc
Function Documentation
void IP_read_byte (void * address, uint8_t * val)
Reads byte from the device.
Parameters:
*address - virtual address of the register to be read
*val - structure containing information about the channel/link we are using
Definition at line 35 of file k_pscip.c.
Referenced by checkmem_device(), k_pscip_rdlinkstat(), k_pscip_rdwave(), k_pscip_read(), k_pscip_wrhiprio(), k_pscip_write(), k_pscip_wrwave(), and pscip_ioctl().
void IP_read_word (void * address, uint16_t * val)
Reads word from the device.
Parameters:
*address - virtual address of the register to be read
*val - structure containing information about the channel/link we are using
Definition at line 47 of file k_pscip.c.
Referenced by k_if_handle_irq(), k_pscip_dump_all_registers(), k_pscip_rdfpgastat(), k_pscip_rdwave(), k_pscip_read(), k_pscip_wait_linkdown(), k_pscip_wrhiprio(), k_pscip_write(), k_pscip_wrwave(), and pscip_irq_handler().
void IP_write_byte (void * address, uint8_t val)
Writing byte to the device.
Parameters:
*address - virtual address of the register to be writen to
*val - structure containing information about the channel/link we are using
Definition at line 60 of file k_pscip.c.
Referenced by k_pscip_clear_err_counter(), and pscip_ioctl().
void IP_write_word (void * address, uint16_t val)
Writing word to the device.
Parameters:
*address - virtual address of the register to be writen to
*val - structure containing information about the channel/link we are using
Definition at line 73 of file k_pscip.c.
Referenced by k_irq_disable(), k_irq_enable(), k_pscip_clear_err_counter(), k_pscip_rdwave(), k_pscip_read(), k_pscip_reset(), k_pscip_wait_linkdown(), k_pscip_wrhiprio(), k_pscip_write(), k_pscip_wrwave(), and pscip_irq_handler().
int k_pscip_clear_err_counter (pscip_t * val, int id_pscip, pscip_Dev dev)
Clean error counter in FPGA status register.
Error coutner indicates the number of errors which occured (ex. due to transmition error). The couter is clean before every read/write function from/to PS
Parameters:
*val - structure containing information about the channel/link we are using
id_pscip - number of the device (IP) we are using, if negative value, the device passed by third argument is used
dev - device structure contaning informatin about the device (IP)
Definition at line 951 of file k_pscip.c.
References pscip_t::chan, IP_write_byte(), IP_write_word(), num_pscip, npscip_Dev::pIP_IOspace, PSCIP_ERRCLEAR_MSK, PSCIP_FPGA_HIGH, and PSCIP_FPGA_LOW.
Referenced by pscip_ioctl().
int k_pscip_dump_all_registers (pscip_t * val, int id_pscip, pscip_Dev dev)
Dumps content of all the registers of both IPs on the carrier and of Local Space O (BADR 2) on the Carrier.
Local Space 0 contains IP A/B control registers, revision ID and status register. It does not metter which IP calles the function, it always dumps information for entire carrier address I/O space used for interfacing IPs IF __DEBUG__ defined, it also interprets content of registers in FPGA status register of calling IP and content of PCI Carrier Status register
Parameters:
*val - structure containing information about the channel/link we are using
id_pscip - number of the device (IP) we are using, if negative value, the device passed by third argument is used
dev - device structure contaning informatin about the device (IP)
Definition at line 974 of file k_pscip.c.
References pscip_t::chan, IP_read_word(), npscip_Dev::IPnumber, npscip_Dev::pIP_IOspace, npscip_Dev::pIPinterfaceReg, npscip_Dev::pPCIinterfaceReg, PSCIP_CHAN_OFFSET, and PSCIP_IP_OFFSET.
Referenced by pscip_ioctl().
int k_pscip_rdfpgastat (pscip_fpga_t * val, int id_pscip, pscip_Dev dev)
Read FPGA status register FPGA status register is for debugging purposes and reflects the error status of the FPGA.
Parameters:
*val - structure reflecting status registers in FPGA - is filled with IP debug information
id_pscip - number of the device (IP) we are using, if negative value, the device passed by third argument is used
dev - device structure contaning informatin about the device (IP)
Definition at line 849 of file k_pscip.c.
References pscip_fpga_t::channel, pscip_fpga_t::high_data, IP_read_word(), pscip_fpga_t::low_data, pscip_fpga_t::mid_data, num_pscip, npscip_Dev::pIP_IOspace, PSCIP_FPGA_HIGH, PSCIP_FPGA_LOW, and PSCIP_FPGA_MID.
Referenced by IP_DEBUG_read_errors(), pscip_ioctl(), and pscip_read_proc().
int k_pscip_rdlinkstat (pscip_t * val, int id_pscip, pscip_Dev dev)
Read link status.
Reads FPGA status register
Parameters:
*val - structure reflecting status registers in FPGA - is filled with IP debug information
id_pscip - number of the device (IP) we are using, if negative value, the device passed by third argument is used
dev - device structure contaning informatin about the device (IP)
Definition at line 803 of file k_pscip.c.
References pscip_t::address, pscip_t::chan, pscip_t::data, IP_read_byte(), num_pscip, npscip_Dev::pIP_IOspace, PSCIP_HPRIOWRITE_STAT, PSCIP_PARAM_ERR, PSCIP_RDWAVE_IDX, PSCIP_RDWAVE_STAT, PSCIP_READ_IDX, PSCIP_READ_STAT, PSCIP_WRHPRIO_IDX, PSCIP_WRITE_IDX, PSCIP_WRITE_STAT, PSCIP_WRWAVE_IDX, and PSCIP_WRWAVE_STAT.
Referenced by pscip_ioctl().
int k_pscip_rdstatistics (pscip_stats_t * val, int id_pscip, pscip_Dev dev)
Read transmission statistics.
Retursn to the user all the information about errors stored in device structure during operation of the driver. It does not read informatin from IP but rather from device structure flags.
Parameters:
*val - structure filled with the information about errors
id_pscip - number of the device (IP) we are using, if negative value, the device passed by third argument is used
dev - device structure contaning informatin about the device (IP)
Definition at line 884 of file k_pscip.c.
References __DEBUG__, pscip_stats_t::channel, pscip_stats_t::err_flag, pscip_stats_t::link_err_flag, pscip_stats_t::linkdown_cnt, num_pscip, pscip_stats_t::rx, npscip_Dev::stats, pscip_stats_t::tx, and pscip_stats_t::txerr_cnt.
Referenced by pscip_ioctl().
int k_pscip_rdwave (pscip_t * val, int id_pscip, pscip_Dev dev)
Execute reading action Function reads data (2 words) of a waveform from given address in PS.
Parameters:
*val - structure containing information about the channel/link we are using
id_pscip - number of the device (IP) we are using, if negative value, the device passed by third argument is used
dev - device structure contaning informatin about the device (IP)
Definition at line 693 of file k_pscip.c.
References pscip_t::address, pscip_t::chan, pscip_stats_t::cntrl_stat, pscip_t::data, pscip_stats_t::err_flag, IP_read_byte(), IP_read_word(), IP_write_word(), npscip_Dev::irqflag, k_pscip_wait_linkdown(), npscip_Dev::lock, num_pscip, npscip_Dev::pIP_IOspace, PSCIP_BUSY_TOUT, PSCIP_DSP_MSK, PSCIP_ERROR_MSK, PSCIP_INPUTBUF_MSK, PSCIP_IRQ_DONE, PSCIP_IRQ_REQUEST, PSCIP_IRQ_SERVED, PSCIP_LINK_ERR, PSCIP_LINK_MSK, PSCIP_LINKDOWN_MSK, PSCIP_RDWAVE_DATA, PSCIP_RDWAVE_REG, PSCIP_RDWAVE_STAT, PSCIP_REMLOC_MSK, PSCIP_TOUT_ERR, PSCIP_TX_ERR, npscip_Dev::queue, queue_flag, pscip_stats_t::rx, pscip_t::stat, and npscip_Dev::stats.
Referenced by pscip_ioctl().
int k_pscip_read (pscip_t * val, int id_pscip, pscip_Dev dev)
Execute reading action.
Function reads data (2 words) from a given address in PS
Parameters:
*val - structure containing information about the channel/link we are using
id_pscip - number of the device (IP) we are using, if negative value, the device passed by third argument is used
dev - device structure contaning informatin about the device (IP)
Definition at line 431 of file k_pscip.c.
References pscip_t::address, pscip_t::chan, pscip_stats_t::cntrl_stat, pscip_t::data, pscip_stats_t::err_flag, IP_read_byte(), IP_read_word(), IP_write_word(), npscip_Dev::irqflag, k_pscip_wait_linkdown(), npscip_Dev::lock, num_pscip, npscip_Dev::pIP_IOspace, PSCIP_BUSY_TOUT, PSCIP_DSP_MSK, PSCIP_ERROR_MSK, PSCIP_INPUTBUF_MSK, PSCIP_IRQ_DONE, PSCIP_IRQ_REQUEST, PSCIP_IRQ_SERVED, PSCIP_LINK_ERR, PSCIP_LINK_MSK, PSCIP_LINKDOWN_MSK, PSCIP_READ_ADDR, PSCIP_READ_DATA, PSCIP_READ_REG, PSCIP_READ_STAT, PSCIP_REMLOC_MSK, PSCIP_TOUT_ERR, PSCIP_TX_ERR, npscip_Dev::queue, queue_flag, pscip_stats_t::rx, pscip_t::stat, and npscip_Dev::stats.
Referenced by pscip_ioctl(), and pscip_thread().
int k_pscip_reset (int id_pscip, pscip_Dev dev)
Reset IP.
This is a hardware reset which is triggered from the Carrier.
Parameters:
id_pscip - number of the device (IP) we are using, if negative value, the device passed by third argument is used
dev - device structure contaning informatin about the device (IP)
Definition at line 919 of file k_pscip.c.
References IP_RESET, IP_write_word(), npscip_Dev::IPnumber, num_pscip, and npscip_Dev::pIPinterfaceReg.
Referenced by pscip_ioctl(), and pscip_write_proc().
int k_pscip_wait_linkdown (pscip_t * val, int id_pscip, pscip_Dev dev)
Wait after linkdown.
Wait some seconds after a linkdown event, maybe to avoid requesting data after a local control unit reboot
Parameters:
*val - structure containing information about the channel/link we are using
id_pscip - number of the device (IP) we are using, if negative value, the device passed by third argument is used
dev - device structure contaning informatin about the device (IP)
Definition at line 92 of file k_pscip.c.
References pscip_t::chan, pscip_stats_t::err_flag, IP_read_word(), IP_write_word(), pscip_stats_t::linkdown_cnt, num_pscip, npscip_Dev::pIP_IOspace, PSCIP_ERRCLEAR_MSK, PSCIP_ERRCNT_MSK, PSCIP_FPGA_HIGH, PSCIP_FPGA_LOW, PSCIP_LINK_ERR, PSCIP_LINKDOWN_MSK, PSCIP_LINKDOWN_TOUT, npscip_Dev::stats, and npscip_Dev::tv.
Referenced by k_pscip_rdwave(), k_pscip_read(), k_pscip_wrhiprio(), k_pscip_write(), and k_pscip_wrwave().
int k_pscip_wrhiprio (pscip_t * val, int id_pscip, pscip_Dev dev)
Execute high priority PS-current setting.
Parameters:
*val - structure containing information about the channel/link we are using
id_pscip - number of the device (IP) we are using, if negative value, the device passed by third argument is used
dev - device structure contaning informatin about the device (IP)
Definition at line 163 of file k_pscip.c.
References pscip_t::address, pscip_t::chan, pscip_stats_t::cntrl_stat, pscip_t::data, pscip_stats_t::err_flag, IP_read_byte(), IP_read_word(), IP_write_word(), npscip_Dev::irqflag, k_pscip_wait_linkdown(), npscip_Dev::lock, num_pscip, npscip_Dev::pIP_IOspace, PSCIP_BUSY_TOUT, PSCIP_DSP_MSK, PSCIP_ECHO_MSK, PSCIP_ERROR_MSK, PSCIP_HPRIOWRITE_DATA, PSCIP_HPRIOWRITE_REG, PSCIP_HPRIOWRITE_STAT, PSCIP_INPUTBUF_MSK, PSCIP_IRQ_DONE, PSCIP_IRQ_REQUEST, PSCIP_IRQ_SERVED, PSCIP_LINK_ERR, PSCIP_LINK_MSK, PSCIP_LINKDOWN_MSK, PSCIP_MISMATCH_ERR, PSCIP_REMLOC_MSK, PSCIP_TOUT_ERR, PSCIP_TX_ERR, npscip_Dev::queue, queue_flag, pscip_t::stat, npscip_Dev::stats, and pscip_stats_t::tx.
Referenced by pscip_ioctl(), and pscip_write_proc().
int k_pscip_write (pscip_t * val, int id_pscip, pscip_Dev dev)
Execute writing action.
The function writes given data (2 words) to given address in the PS, the information is passed with a given status.
Parameters:
*val - structure containing information about the channel/link we are using
id_pscip - number of the device (IP) we are using, if negative value, the device passed by third argument is used
dev - device structure contaning informatin about the device (IP)
Definition at line 303 of file k_pscip.c.
References pscip_t::address, pscip_t::chan, pscip_stats_t::cntrl_stat, pscip_t::data, pscip_stats_t::err_flag, IP_read_byte(), IP_read_word(), IP_write_word(), npscip_Dev::irqflag, k_pscip_wait_linkdown(), npscip_Dev::lock, num_pscip, npscip_Dev::pIP_IOspace, PSCIP_BUSY_TOUT, PSCIP_DSP_MSK, PSCIP_ECHO_MSK, PSCIP_ERROR_MSK, PSCIP_INPUTBUF_MSK, PSCIP_IRQ_DONE, PSCIP_IRQ_REQUEST, PSCIP_IRQ_SERVED, PSCIP_LINK_ERR, PSCIP_LINK_MSK, PSCIP_LINKDOWN_MSK, PSCIP_MISMATCH_ERR, PSCIP_REMLOC_MSK, PSCIP_TOUT_ERR, PSCIP_TX_ERR, PSCIP_WRITE_DATA, PSCIP_WRITE_REG, PSCIP_WRITE_STAT, npscip_Dev::queue, queue_flag, pscip_t::stat, npscip_Dev::stats, and pscip_stats_t::tx.
Referenced by pscip_ioctl(), and pscip_write_proc().
int k_pscip_wrstat (pscip_t * , int , pscip_Dev)
int k_pscip_wrwave (pscip_t * val, int id_pscip, pscip_Dev dev)
Write wave value.
Function writes datat (2 words) of waveform to given address in PS
Parameters:
*val - structure containing information about the channel/link we are using
id_pscip - number of the device (IP) we are using, if negative value, the device passed by third argument is used
dev - device structure contaning informatin about the device (IP)
Definition at line 561 of file k_pscip.c.
References pscip_t::address, pscip_t::chan, pscip_stats_t::cntrl_stat, pscip_t::data, pscip_stats_t::err_flag, IP_read_byte(), IP_read_word(), IP_write_word(), npscip_Dev::irqflag, k_pscip_wait_linkdown(), npscip_Dev::lock, num_pscip, npscip_Dev::pIP_IOspace, PSCIP_BUSY_TOUT, PSCIP_DSP_MSK, PSCIP_ECHO_MSK, PSCIP_ERROR_MSK, PSCIP_INPUTBUF_MSK, PSCIP_IRQ_DONE, PSCIP_IRQ_REQUEST, PSCIP_IRQ_SERVED, PSCIP_LINK_ERR, PSCIP_LINK_MSK, PSCIP_LINKDOWN_MSK, PSCIP_MISMATCH_ERR, PSCIP_REMLOC_MSK, PSCIP_TOUT_ERR, PSCIP_TX_ERR, PSCIP_WRWAVE_DATA, PSCIP_WRWAVE_REG, PSCIP_WRWAVE_STAT, npscip_Dev::queue, queue_flag, pscip_t::stat, npscip_Dev::stats, and pscip_stats_t::tx.
Referenced by pscip_ioctl(), and pscip_write_proc().