Z:/Project/development/PSCIP/driver/k_pscip.c File Reference
Z:/Project/development/PSCIP/driver/k_pscip.c File Reference
Contains function directly interfacing hardware/kernel.
Functions
MODULE_DEVICE_TABLE (pci, ids)
Registering the table defining a list of the different types of CI devices that the driver supports.
void IP_read_byte (void *address, uint8_t *val)
Reads byte from the device.
void IP_read_word (void *address, uint16_t *val)
Reads word from the device.
void IP_write_byte (void *address, uint8_t val)
Writing byte to the device.
void IP_write_word (void *address, uint16_t val)
Writing word to the device.
int k_pscip_wait_linkdown (pscip_t *val, int id_pscip, pscip_Dev dev)
Wait after linkdown.
int k_pscip_wrhiprio (pscip_t *val, int id_pscip, pscip_Dev dev)
Execute high priority PS-current setting.
int k_pscip_write (pscip_t *val, int id_pscip, pscip_Dev dev)
Execute writing action.
int k_pscip_read (pscip_t *val, int id_pscip, pscip_Dev dev)
Execute reading action.
int k_pscip_wrwave (pscip_t *val, int id_pscip, pscip_Dev dev)
Write wave value.
int k_pscip_rdwave (pscip_t *val, int id_pscip, pscip_Dev dev)
Execute reading action Function reads data (2 words) of a waveform from given address in PS.
int k_pscip_rdlinkstat (pscip_t *val, int id_pscip, pscip_Dev dev)
Read link status.
int k_pscip_rdfpgastat (pscip_fpga_t *val, int id_pscip, pscip_Dev dev)
Read FPGA status register FPGA status register is for debugging purposes and reflects the error status of the FPGA.
int k_pscip_rdstatistics (pscip_stats_t *val, int id_pscip, pscip_Dev dev)
Read transmission statistics.
int k_pscip_reset (int id_pscip, pscip_Dev dev)
Reset IP.
int k_pscip_clear_err_counter (pscip_t *val, int id_pscip, pscip_Dev dev)
Clean error counter in FPGA status register.
int k_pscip_dump_all_registers (pscip_t *val, int id_pscip, pscip_Dev dev)
Dumps content of all the registers of both IPs on the carrier and of Local Space O (BADR 2) on the Carrier.
int k_irq_enable (pscip_Dev dev)
Does hardware magic to enable interrupt on calling IP.
int k_irq_disable (pscip_Dev dev)
Does hardware magic to disable interrupt on calling IP.
int k_if_handle_irq (pscip_Dev dev)
Veryfies the source of the interrupt.
Variables
static int num_pscip = 0
Number of registered devices.
static npscip_Dev pscip_devices [PSCIP_MAX_DEV]
Static table of structures holding device datea.
static struct pci_device_id ids []
The structure is used to define a list of the different types of PCI devices that a driver supports.
Detailed Description
Contains function directly interfacing hardware/kernel.
The file can be viewed like a lower layer of driver interface PSCIP Driver for Linux Kernel Functions to access hardware
GG - 18.07.2005: First implementation GG - 08.02.2006: When setting status writew in the same stat and addr register
22/10/2008 - Start of porting the driver :
from 2.4.x to 2.6.x
from VME to PCIGG
Definition in file k_pscip.c.
Function Documentation
void IP_read_byte (void * address, uint8_t * val)
Reads byte from the device.
Parameters:
*address - virtual address of the register to be read
*val - structure containing information about the channel/link we are using
Definition at line 35 of file k_pscip.c.
Referenced by checkmem_device(), k_pscip_rdlinkstat(), k_pscip_rdwave(), k_pscip_read(), k_pscip_wrhiprio(), k_pscip_write(), k_pscip_wrwave(), and pscip_ioctl().
void IP_read_word (void * address, uint16_t * val)
Reads word from the device.
Parameters:
*address - virtual address of the register to be read
*val - structure containing information about the channel/link we are using
Definition at line 47 of file k_pscip.c.
Referenced by k_if_handle_irq(), k_pscip_dump_all_registers(), k_pscip_rdfpgastat(), k_pscip_rdwave(), k_pscip_read(), k_pscip_wait_linkdown(), k_pscip_wrhiprio(), k_pscip_write(), k_pscip_wrwave(), and pscip_irq_handler().
void IP_write_byte (void * address, uint8_t val)
Writing byte to the device.
Parameters:
*address - virtual address of the register to be writen to
*val - structure containing information about the channel/link we are using
Definition at line 60 of file k_pscip.c.
Referenced by k_pscip_clear_err_counter(), and pscip_ioctl().
void IP_write_word (void * address, uint16_t val)
Writing word to the device.
Parameters:
*address - virtual address of the register to be writen to
*val - structure containing information about the channel/link we are using
Definition at line 73 of file k_pscip.c.
Referenced by k_irq_disable(), k_irq_enable(), k_pscip_clear_err_counter(), k_pscip_rdwave(), k_pscip_read(), k_pscip_reset(), k_pscip_wait_linkdown(), k_pscip_wrhiprio(), k_pscip_write(), k_pscip_wrwave(), and pscip_irq_handler().
int k_if_handle_irq (pscip_Dev dev)
Veryfies the source of the interrupt.
It checks whether the interupt was triggered by an IP represented by dev device structure registerred with given interrupt handler
Parameters:
dev - device structure contaning informatin about the device (IP)
Returns:
- returns number of channel which triggered the interrupt or error
Definition at line 1105 of file k_pscip.c.
References IP_INT0_A, IP_INT0_B, IP_INT1_A, IP_INT1_B, IP_read_word(), IP_STATUS, npscip_Dev::IPnumber, and npscip_Dev::pIPinterfaceReg.
Referenced by pscip_irq_handler().
int k_irq_disable (pscip_Dev dev)
Does hardware magic to disable interrupt on calling IP.
Called when last reference to give IP (/dev/pscipX) is closed
Parameters:
dev - device structure contaning informatin about the device (IP)
Definition at line 1079 of file k_pscip.c.
References IP_A_CONTROL, IP_B_CONTROL, IP_write_word(), npscip_Dev::IPnumber, and npscip_Dev::pIPinterfaceReg.
Referenced by pscip_release().
int k_irq_enable (pscip_Dev dev)
Does hardware magic to enable interrupt on calling IP.
Called when first reference to give IP (/dev/pscipX) is openned Interrupt 0 is triggered by channel/link 0 Interrupt 1 is triggered by channel/link 1
Parameters:
dev - device structure contaning informatin about the device (IP)
Definition at line 1055 of file k_pscip.c.
References IP_A_CONTROL, IP_B_CONTROL, IP_INT0_EN, IP_INT1_EN, IP_write_word(), npscip_Dev::IPnumber, and npscip_Dev::pIPinterfaceReg.
Referenced by pscip_open().
int k_pscip_clear_err_counter (pscip_t * val, int id_pscip, pscip_Dev dev)
Clean error counter in FPGA status register.
Error coutner indicates the number of errors which occured (ex. due to transmition error). The couter is clean before every read/write function from/to PS
Parameters:
*val - structure containing information about the channel/link we are using
id_pscip - number of the device (IP) we are using, if negative value, the device passed by third argument is used
dev - device structure contaning informatin about the device (IP)
Definition at line 951 of file k_pscip.c.
References pscip_t::chan, IP_write_byte(), IP_write_word(), num_pscip, npscip_Dev::pIP_IOspace, PSCIP_ERRCLEAR_MSK, PSCIP_FPGA_HIGH, and PSCIP_FPGA_LOW.
Referenced by pscip_ioctl().
int k_pscip_dump_all_registers (pscip_t * val, int id_pscip, pscip_Dev dev)
Dumps content of all the registers of both IPs on the carrier and of Local Space O (BADR 2) on the Carrier.
Local Space 0 contains IP A/B control registers, revision ID and status register. It does not metter which IP calles the function, it always dumps information for entire carrier address I/O space used for interfacing IPs IF __DEBUG__ defined, it also interprets content of registers in FPGA status register of calling IP and content of PCI Carrier Status register
Parameters:
*val - structure containing information about the channel/link we are using
id_pscip - number of the device (IP) we are using, if negative value, the device passed by third argument is used
dev - device structure contaning informatin about the device (IP)
Definition at line 974 of file k_pscip.c.
References pscip_t::chan, IP_read_word(), npscip_Dev::IPnumber, npscip_Dev::pIP_IOspace, npscip_Dev::pIPinterfaceReg, npscip_Dev::pPCIinterfaceReg, PSCIP_CHAN_OFFSET, and PSCIP_IP_OFFSET.
Referenced by pscip_ioctl().
int k_pscip_rdfpgastat (pscip_fpga_t * val, int id_pscip, pscip_Dev dev)
Read FPGA status register FPGA status register is for debugging purposes and reflects the error status of the FPGA.
Parameters:
*val - structure reflecting status registers in FPGA - is filled with IP debug information
id_pscip - number of the device (IP) we are using, if negative value, the device passed by third argument is used
dev - device structure contaning informatin about the device (IP)
Definition at line 849 of file k_pscip.c.
References pscip_fpga_t::channel, pscip_fpga_t::high_data, IP_read_word(), pscip_fpga_t::low_data, pscip_fpga_t::mid_data, num_pscip, npscip_Dev::pIP_IOspace, PSCIP_FPGA_HIGH, PSCIP_FPGA_LOW, and PSCIP_FPGA_MID.
Referenced by IP_DEBUG_read_errors(), pscip_ioctl(), and pscip_read_proc().
int k_pscip_rdlinkstat (pscip_t * val, int id_pscip, pscip_Dev dev)
Read link status.
Reads FPGA status register
Parameters:
*val - structure reflecting status registers in FPGA - is filled with IP debug information
id_pscip - number of the device (IP) we are using, if negative value, the device passed by third argument is used
dev - device structure contaning informatin about the device (IP)
Definition at line 803 of file k_pscip.c.
References pscip_t::address, pscip_t::chan, pscip_t::data, IP_read_byte(), num_pscip, npscip_Dev::pIP_IOspace, PSCIP_HPRIOWRITE_STAT, PSCIP_PARAM_ERR, PSCIP_RDWAVE_IDX, PSCIP_RDWAVE_STAT, PSCIP_READ_IDX, PSCIP_READ_STAT, PSCIP_WRHPRIO_IDX, PSCIP_WRITE_IDX, PSCIP_WRITE_STAT, PSCIP_WRWAVE_IDX, and PSCIP_WRWAVE_STAT.
Referenced by pscip_ioctl().
int k_pscip_rdstatistics (pscip_stats_t * val, int id_pscip, pscip_Dev dev)
Read transmission statistics.
Retursn to the user all the information about errors stored in device structure during operation of the driver. It does not read informatin from IP but rather from device structure flags.
Parameters:
*val - structure filled with the information about errors
id_pscip - number of the device (IP) we are using, if negative value, the device passed by third argument is used
dev - device structure contaning informatin about the device (IP)
Definition at line 884 of file k_pscip.c.
References __DEBUG__, pscip_stats_t::channel, pscip_stats_t::err_flag, pscip_stats_t::link_err_flag, pscip_stats_t::linkdown_cnt, num_pscip, pscip_stats_t::rx, npscip_Dev::stats, pscip_stats_t::tx, and pscip_stats_t::txerr_cnt.
Referenced by pscip_ioctl().
int k_pscip_rdwave (pscip_t * val, int id_pscip, pscip_Dev dev)
Execute reading action Function reads data (2 words) of a waveform from given address in PS.
Parameters:
*val - structure containing information about the channel/link we are using
id_pscip - number of the device (IP) we are using, if negative value, the device passed by third argument is used
dev - device structure contaning informatin about the device (IP)
Definition at line 693 of file k_pscip.c.
References pscip_t::address, pscip_t::chan, pscip_stats_t::cntrl_stat, pscip_t::data, pscip_stats_t::err_flag, IP_read_byte(), IP_read_word(), IP_write_word(), npscip_Dev::irqflag, k_pscip_wait_linkdown(), npscip_Dev::lock, num_pscip, npscip_Dev::pIP_IOspace, PSCIP_BUSY_TOUT, PSCIP_DSP_MSK, PSCIP_ERROR_MSK, PSCIP_INPUTBUF_MSK, PSCIP_IRQ_DONE, PSCIP_IRQ_REQUEST, PSCIP_IRQ_SERVED, PSCIP_LINK_ERR, PSCIP_LINK_MSK, PSCIP_LINKDOWN_MSK, PSCIP_RDWAVE_DATA, PSCIP_RDWAVE_REG, PSCIP_RDWAVE_STAT, PSCIP_REMLOC_MSK, PSCIP_TOUT_ERR, PSCIP_TX_ERR, npscip_Dev::queue, queue_flag, pscip_stats_t::rx, pscip_t::stat, and npscip_Dev::stats.
Referenced by pscip_ioctl().
int k_pscip_read (pscip_t * val, int id_pscip, pscip_Dev dev)
Execute reading action.
Function reads data (2 words) from a given address in PS
Parameters:
*val - structure containing information about the channel/link we are using
id_pscip - number of the device (IP) we are using, if negative value, the device passed by third argument is used
dev - device structure contaning informatin about the device (IP)
Definition at line 431 of file k_pscip.c.
References pscip_t::address, pscip_t::chan, pscip_stats_t::cntrl_stat, pscip_t::data, pscip_stats_t::err_flag, IP_read_byte(), IP_read_word(), IP_write_word(), npscip_Dev::irqflag, k_pscip_wait_linkdown(), npscip_Dev::lock, num_pscip, npscip_Dev::pIP_IOspace, PSCIP_BUSY_TOUT, PSCIP_DSP_MSK, PSCIP_ERROR_MSK, PSCIP_INPUTBUF_MSK, PSCIP_IRQ_DONE, PSCIP_IRQ_REQUEST, PSCIP_IRQ_SERVED, PSCIP_LINK_ERR, PSCIP_LINK_MSK, PSCIP_LINKDOWN_MSK, PSCIP_READ_ADDR, PSCIP_READ_DATA, PSCIP_READ_REG, PSCIP_READ_STAT, PSCIP_REMLOC_MSK, PSCIP_TOUT_ERR, PSCIP_TX_ERR, npscip_Dev::queue, queue_flag, pscip_stats_t::rx, pscip_t::stat, and npscip_Dev::stats.
Referenced by pscip_ioctl(), and pscip_thread().
int k_pscip_reset (int id_pscip, pscip_Dev dev)
Reset IP.
This is a hardware reset which is triggered from the Carrier.
Parameters:
id_pscip - number of the device (IP) we are using, if negative value, the device passed by third argument is used
dev - device structure contaning informatin about the device (IP)
Definition at line 919 of file k_pscip.c.
References IP_RESET, IP_write_word(), npscip_Dev::IPnumber, num_pscip, and npscip_Dev::pIPinterfaceReg.
Referenced by pscip_ioctl(), and pscip_write_proc().
int k_pscip_wait_linkdown (pscip_t * val, int id_pscip, pscip_Dev dev)
Wait after linkdown.
Wait some seconds after a linkdown event, maybe to avoid requesting data after a local control unit reboot
Parameters:
*val - structure containing information about the channel/link we are using
id_pscip - number of the device (IP) we are using, if negative value, the device passed by third argument is used
dev - device structure contaning informatin about the device (IP)
Definition at line 92 of file k_pscip.c.
References pscip_t::chan, pscip_stats_t::err_flag, IP_read_word(), IP_write_word(), pscip_stats_t::linkdown_cnt, num_pscip, npscip_Dev::pIP_IOspace, PSCIP_ERRCLEAR_MSK, PSCIP_ERRCNT_MSK, PSCIP_FPGA_HIGH, PSCIP_FPGA_LOW, PSCIP_LINK_ERR, PSCIP_LINKDOWN_MSK, PSCIP_LINKDOWN_TOUT, npscip_Dev::stats, and npscip_Dev::tv.
Referenced by k_pscip_rdwave(), k_pscip_read(), k_pscip_wrhiprio(), k_pscip_write(), and k_pscip_wrwave().
int k_pscip_wrhiprio (pscip_t * val, int id_pscip, pscip_Dev dev)
Execute high priority PS-current setting.
Parameters:
*val - structure containing information about the channel/link we are using
id_pscip - number of the device (IP) we are using, if negative value, the device passed by third argument is used
dev - device structure contaning informatin about the device (IP)
Definition at line 163 of file k_pscip.c.
References pscip_t::address, pscip_t::chan, pscip_stats_t::cntrl_stat, pscip_t::data, pscip_stats_t::err_flag, IP_read_byte(), IP_read_word(), IP_write_word(), npscip_Dev::irqflag, k_pscip_wait_linkdown(), npscip_Dev::lock, num_pscip, npscip_Dev::pIP_IOspace, PSCIP_BUSY_TOUT, PSCIP_DSP_MSK, PSCIP_ECHO_MSK, PSCIP_ERROR_MSK, PSCIP_HPRIOWRITE_DATA, PSCIP_HPRIOWRITE_REG, PSCIP_HPRIOWRITE_STAT, PSCIP_INPUTBUF_MSK, PSCIP_IRQ_DONE, PSCIP_IRQ_REQUEST, PSCIP_IRQ_SERVED, PSCIP_LINK_ERR, PSCIP_LINK_MSK, PSCIP_LINKDOWN_MSK, PSCIP_MISMATCH_ERR, PSCIP_REMLOC_MSK, PSCIP_TOUT_ERR, PSCIP_TX_ERR, npscip_Dev::queue, queue_flag, pscip_t::stat, npscip_Dev::stats, and pscip_stats_t::tx.
Referenced by pscip_ioctl(), and pscip_write_proc().
int k_pscip_write (pscip_t * val, int id_pscip, pscip_Dev dev)
Execute writing action.
The function writes given data (2 words) to given address in the PS, the information is passed with a given status.
Parameters:
*val - structure containing information about the channel/link we are using
id_pscip - number of the device (IP) we are using, if negative value, the device passed by third argument is used
dev - device structure contaning informatin about the device (IP)
Definition at line 303 of file k_pscip.c.
References pscip_t::address, pscip_t::chan, pscip_stats_t::cntrl_stat, pscip_t::data, pscip_stats_t::err_flag, IP_read_byte(), IP_read_word(), IP_write_word(), npscip_Dev::irqflag, k_pscip_wait_linkdown(), npscip_Dev::lock, num_pscip, npscip_Dev::pIP_IOspace, PSCIP_BUSY_TOUT, PSCIP_DSP_MSK, PSCIP_ECHO_MSK, PSCIP_ERROR_MSK, PSCIP_INPUTBUF_MSK, PSCIP_IRQ_DONE, PSCIP_IRQ_REQUEST, PSCIP_IRQ_SERVED, PSCIP_LINK_ERR, PSCIP_LINK_MSK, PSCIP_LINKDOWN_MSK, PSCIP_MISMATCH_ERR, PSCIP_REMLOC_MSK, PSCIP_TOUT_ERR, PSCIP_TX_ERR, PSCIP_WRITE_DATA, PSCIP_WRITE_REG, PSCIP_WRITE_STAT, npscip_Dev::queue, queue_flag, pscip_t::stat, npscip_Dev::stats, and pscip_stats_t::tx.
Referenced by pscip_ioctl(), and pscip_write_proc().
int k_pscip_wrwave (pscip_t * val, int id_pscip, pscip_Dev dev)
Write wave value.
Function writes datat (2 words) of waveform to given address in PS
Parameters:
*val - structure containing information about the channel/link we are using
id_pscip - number of the device (IP) we are using, if negative value, the device passed by third argument is used
dev - device structure contaning informatin about the device (IP)
Definition at line 561 of file k_pscip.c.
References pscip_t::address, pscip_t::chan, pscip_stats_t::cntrl_stat, pscip_t::data, pscip_stats_t::err_flag, IP_read_byte(), IP_read_word(), IP_write_word(), npscip_Dev::irqflag, k_pscip_wait_linkdown(), npscip_Dev::lock, num_pscip, npscip_Dev::pIP_IOspace, PSCIP_BUSY_TOUT, PSCIP_DSP_MSK, PSCIP_ECHO_MSK, PSCIP_ERROR_MSK, PSCIP_INPUTBUF_MSK, PSCIP_IRQ_DONE, PSCIP_IRQ_REQUEST, PSCIP_IRQ_SERVED, PSCIP_LINK_ERR, PSCIP_LINK_MSK, PSCIP_LINKDOWN_MSK, PSCIP_MISMATCH_ERR, PSCIP_REMLOC_MSK, PSCIP_TOUT_ERR, PSCIP_TX_ERR, PSCIP_WRWAVE_DATA, PSCIP_WRWAVE_REG, PSCIP_WRWAVE_STAT, npscip_Dev::queue, queue_flag, pscip_t::stat, npscip_Dev::stats, and pscip_stats_t::tx.
Referenced by pscip_ioctl(), and pscip_write_proc().
MODULE_DEVICE_TABLE (pci , ids)
Registering the table defining a list of the different types of CI devices that the driver supports.
Variable Documentation
struct pci_device_id ids[] [static]
Initial value:
 {
 { PCI_DEVICE(PCI_VENDOR_ID_TEWS, PCI_DEVICE_ID_TCPI100_PCI), },
 { PCI_DEVICE(PCI_VENDOR_ID_TEWS, PCI_DEVICE_ID_TCP221_cPCI), },
 { 0, }
}
The structure is used to define a list of the different types of PCI devices that a driver supports.
Definition at line 21 of file k_pscip.c.
int num_pscip = 0 [static]
Number of registered devices.
Definition at line 16 of file k_pscip.c.
Referenced by k_pscip_clear_err_counter(), k_pscip_rdfpgastat(), k_pscip_rdlinkstat(), k_pscip_rdstatistics(), k_pscip_rdwave(), k_pscip_read(), k_pscip_reset(), k_pscip_wait_linkdown(), k_pscip_wrhiprio(), k_pscip_write(), k_pscip_wrwave(), and probe().
npscip_Dev pscip_devices[PSCIP_MAX_DEV] [static]
Static table of structures holding device datea.
Definition at line 18 of file k_pscip.c.
Referenced by checkmem_device(), init_pscip(), init_pscip_module(), probe(), pscip_read_proc(), pscip_write_proc(), and remove().