Z:/Project/development/PSCIP/driver/pscip.c File Reference
Z:/Project/development/PSCIP/driver/pscip.c File Reference
PSCIP Driver for Linux Kernel 2.6.x-development version - main file.
#include <linux/init.h>
#include <linux/module.h>
#include <linux/moduleparam.h>
#include <linux/fs.h>
#include <linux/types.h>
#include <linux/kdev_t.h>
#include <linux/cdev.h>
#include <linux/kernel.h>
#include <linux/pci.h>
#include <linux/ioport.h>
#include <linux/interrupt.h>
#include <asm/spinlock.h>
#include <asm/semaphore.h>
#include <asm/system.h>
#include <asm/io.h>
#include <linux/proc_fs.h>
#include <linux/errno.h>
#include <linux/delay.h>
#include <linux/time.h>
#include <asm/uaccess.h>
#include <asm/atomic.h>
#include "debug_pscip.h"
#include "pscip.h"
#include "k_pscip.h"
#include "k_pscip.c"
#include "debug_pscip.c"
Defines
#define __DEBUG__
If defined, enables debug printk to logfile.
Functions
MODULE_LICENSE ("GPL")
< If defined, Real Time IP enabled.
module_param (hack_driver, int, 0)
Macro defining hack_driver module parameters.
module_param (pscip_major, int, 0)
Macro defining pscip_major module parameters.
MODULE_PARM_DESC (pscip_major,"PSCIP major number, if defined by user")
MODULE_PARM_DESC (pscip_dev_number,"PSCIP number of devices which can be run using this driver")
MODULE_PARM_DESC (hack_driver,"PSCIP special functions for developers:\n -- no func implemented at the moment --")
void pscip_irq_bh0 (unsigned long)
Tasklet used to send a SIGIO to user space, chan 0.
void pscip_irq_bh1 (unsigned long)
Tasklet used to send a SIGIO to user space, chan 0.
int pscip_assign_irq (pscip_Dev dev)
Function registering interrupt in the cernel.
irqreturn_t pscip_irq_handler (int pciirq, void *dev_id, struct pt_regs *regs)
Interrupt hanlder.
static int pscip_open (struct inode *, struct file *)
Function called when the node represeting driver is opened.
static int pscip_release (struct inode *, struct file *)
Function called when the node represeting driver is closed.
static int pscip_ioctl (struct inode *, struct file *, unsigned int, unsigned long)
Function implementing ioctl control.
static int probe (struct pci_dev *dev, const struct pci_device_id *id)
Function called when the device (Carrier card) is detected on the PCI bus.
static void remove (struct pci_dev *pcidev)
Function called when the device (Carrier) is removed from the PCI bus.
static int pscip_read_proc (char *page, char **start, off_t offset, int count, int *eof, void *data)
Create a proc filesystem read entry.
static int pscip_write_proc (struct file *filp, const char *buffer, unsigned long count, void *data)
creat a proc file system write entry
static int pscip_procfs_register (void)
Register proc filesystem entries.
static void init_pscip (int i)
Initializatin of interrupt and concurrency related mechanisms.
static int checkmem_device (int i)
Checks whether device is in the slot by reading specific registers holdilng IP IDs.
static void exit_pscip_module (void)
Function called when the module is deinserted.
static int init_pscip_module (void)
Function called when the driver/module is inserted.
module_init (init_pscip_module)
Registering first function to be called when inserting the module.
module_exit (exit_pscip_module)
Registering last function to be called when de-inserting the module.
Variables
static int queue_flag = 0
Flag used in waitqueue mechanism.
int pscip_minor = PSCIP_MINOR_NUMBER
Global variable with first minor numer associated with the driver.
static char ver [10] = "1.0"
Module/driver version.
const char * module_name = "pscip"
module name.
static int pscip_dev_number = 0
Module parameter - number of IPs.
static int hack_driver = 0
Module paramter - options for developer.
static int pscip_major
Global variable with major numer associated with the driver.
static struct file_operations pscip_fops
File operation structure.
static struct pci_driver pscip_driver
Structure describing PCI device (IP).
static pscip_Proc pscip_procdev
Proc filesystem structure .
static struct proc_dir_entry * proc_model_dir
Structure defining entry in proc file system.
Detailed Description
PSCIP Driver for Linux Kernel 2.6.x-development version - main file.
GG - 19.07.2005: First implementation
22/10/2008 - Start of porting the driver :
from 2.4.x to 2.6.x
from VME to PCIGG 12/20008 - finalizing first release
Definition in file pscip.c.
Define Documentation
#define __DEBUG__
If defined, enables debug printk to logfile.
Can be very useful when trying to determine bug location Every function prints information when beginning and when finishing Functions whose code is in pscip.c file print informatin starting with DEBUG_M and are not intended Fundtions whose code is in k_pscip.c file print information starting with DEBUG_K and are intended Funnctions whose code is in debug_pscip. file print information starting with DEBUG and are even more inteded
Definition at line 69 of file pscip.c.
Referenced by k_pscip_rdstatistics().
Function Documentation
static int checkmem_device (int i) [static]
Checks whether device is in the slot by reading specific registers holdilng IP IDs.
Definition at line 1174 of file pscip.c.
References IP_read_byte(), pscip_devices, PSCIP_MANIFAC_ID, PSCIP_MANIFAC_REG, PSCIP_MODEL_ID, and PSCIP_MODEL_REG.
Referenced by probe().
static void exit_pscip_module (void) [static]
Function called when the module is deinserted.
Clean up module from kernel - all unregister staff
Definition at line 1417 of file pscip.c.
References module_name, proc_model_dir, pscip_dev_number, pscip_driver, pscip_major, and pscip_minor.
static void init_pscip (int i) [static]
Initializatin of interrupt and concurrency related mechanisms.
The functions registers tasklests for each channel on the calling IP, registers spinlocks and waitqueues.
Parameters:
i - number of device (IP) in the device structure
Definition at line 1135 of file pscip.c.
References pscip_devices, pscip_irq_bh0(), pscip_irq_bh1(), PSCIP_LINKDOWN_TOUT, and npscip_Dev::tv.
Referenced by probe().
static int init_pscip_module (void) [static]
Function called when the driver/module is inserted.
It establishes how many devices (IPs) the driver will enable to operate. It registers major and minor numbers for the driver, registers driver, prepare memory for device structure, initializes device structure table with 0/null values and create proc_fs entries in /proc/driver folder.
Definition at line 1455 of file pscip.c.
References npscip_Dev::carrier_number, FALSE, npscip_Dev::IP_in_slot, npscip_Dev::IP_IOspaceAddr, npscip_Dev::IP_IOspaceFlags, npscip_Dev::IP_IOspaceLen, npscip_Dev::IPinterfaceAddr, npscip_Dev::IPinterfaceFlags, npscip_Dev::IPinterfaceLen, npscip_Dev::IPnumber, npscip_Dev::irq, npscip_Dev::irqdata, npscip_Dev::irqflag, npscip_Dev::pciaddr, npscip_Dev::PCIinterfaceAddr, npscip_Dev::PCIinterfaceFlags, npscip_Dev::PCIinterfaceLen, npscip_Dev::pIPinterfaceReg, npscip_Dev::pPCIinterfaceReg, PSCIP_DEFAULT_DEV, pscip_dev_number, pscip_devices, pscip_driver, pscip_major, PSCIP_MAX_CHAN, PSCIP_MAX_DEV, pscip_minor, pscip_procfs_register(), and npscip_Dev::refcount.
module_exit (exit_pscip_module)
Registering last function to be called when de-inserting the module.
module_init (init_pscip_module)
Registering first function to be called when inserting the module.
MODULE_LICENSE ("GPL")
< If defined, Real Time IP enabled.
RTAI is inharited from Electtra and not changed/looked into Determines the driver's licencing. If missing the kernel shouts about taining it
module_param (pscip_major , int , 0)
Macro defining pscip_major module parameters.
module_param (hack_driver , int , 0)
Macro defining hack_driver module parameters.
MODULE_PARM_DESC (hack_driver , "PSCIP special functions for developers:\n -- no func implemented at the moment --")
MODULE_PARM_DESC (pscip_dev_number , "PSCIP number of devices which can be run using this driver")
MODULE_PARM_DESC (pscip_major , "PSCIP major number, if defined by user")
static int probe (struct pci_dev * dev, const struct pci_device_id * id) [static]
Function called when the device (Carrier card) is detected on the PCI bus.
It performs most of the initialization for both IPs on the carrier and registers the character device in the kernel.
Parameters:
*dev - PCI device structure representing PCI device
*id -
Definition at line 1202 of file pscip.c.
References npscip_Dev::carrier_number, npscip_Dev::cdev, checkmem_device(), FALSE, init_pscip(), npscip_Dev::IP_in_slot, npscip_Dev::IP_IOspaceAddr, npscip_Dev::IP_IOspaceFlags, npscip_Dev::IP_IOspaceLen, npscip_Dev::IPinterfaceAddr, npscip_Dev::IPinterfaceFlags, npscip_Dev::IPinterfaceLen, npscip_Dev::IPnumber, npscip_Dev::irq, MAX_NUMER_OF_IPs_ON_CARRIER, module_name, num_pscip, npscip_Dev::pciaddr, npscip_Dev::pcidev, npscip_Dev::PCIinterfaceAddr, npscip_Dev::PCIinterfaceFlags, npscip_Dev::PCIinterfaceLen, npscip_Dev::pIP_IOspace, npscip_Dev::pIPinterfaceReg, npscip_Dev::pPCIinterfaceReg, PSCIP_CHAN_OFFSET, pscip_dev_number, pscip_devices, pscip_fops, pscip_get_PCI_info(), PSCIP_IP_OFFSET, pscip_major, pscip_minor, npscip_Dev::pscip_number, and TRUE.
int pscip_assign_irq (pscip_Dev dev)
Function registering interrupt in the cernel.
Calles function which registers interrupt handler.
Parameters:
dev - device structure
Definition at line 844 of file pscip.c.
References npscip_Dev::irq, and pscip_irq_handler().
Referenced by pscip_open().
static int pscip_ioctl (struct inode * inode, struct file * filp, unsigned int cmd, unsigned long arg) [static]
Function implementing ioctl control.
Used to read-write I/O operations and IP configuration.
Parameters:
*inode - contains cdev structure, allows to get our device structure
*filp - pointer to a file structure cmd - command to be executed
arg - data passed from/to kernel space
Definition at line 302 of file pscip.c.
References pscip_t::address, pscip_t::chan, id_pscip, IP_DEBUG_read_FPGA_stat(), IP_DEBUG_read_IP_interface_reg(), IP_read_byte(), IP_write_byte(), k_pscip_clear_err_counter(), k_pscip_dump_all_registers(), k_pscip_rdfpgastat(), k_pscip_rdlinkstat(), k_pscip_rdstatistics(), k_pscip_rdwave(), k_pscip_read(), k_pscip_reset(), k_pscip_wrhiprio(), k_pscip_write(), k_pscip_wrwave(), npscip_Dev::pciaddr, npscip_Dev::pIP_IOspace, npscip_Dev::pIPinterfaceReg, PSCIP_CLRCOUNTER, PSCIP_DUMPFPGAREGS, PSCIP_FPGA_REG, PSCIP_PCIADDR, PSCIP_RDFPGASTAT, PSCIP_RDLINKSTAT, PSCIP_RDSTATISTICS, PSCIP_RDWAVE, PSCIP_READ, PSCIP_READIPREG, PSCIP_RESET, PSCIP_WRHIPRIO, PSCIP_WRITE, PSCIP_WRITEIPREG, PSCIP_WRWAVE, npscip_Dev::sem, pscip_t::stat, and val.
void pscip_irq_bh0 (unsigned long data)
Tasklet used to send a SIGIO to user space, chan 0.
pscip_irq_bh0 - called for interrupts on channel 0 of IP tasklets are a special function that may be scheduled to run, in software interrupt context, at a system-determined safe time.
They may be scheduled to run multiple times, but tasklet scheduling is not cumulative; the tasklet runs only once, even if it is requested repeatedly before it is launched. NOTE: tasklet function should return irqreturn_t but here this functions are initialized in "unconventional" way and they need to return void.....
Parameters:
data - data to be passed to the tasklet - anything cased to unsigned long - probably pointer
Definition at line 686 of file pscip.c.
References npscip_Dev::lock, npscip_Dev::queue, and queue_flag.
Referenced by init_pscip().
void pscip_irq_bh1 (unsigned long data)
Tasklet used to send a SIGIO to user space, chan 0.
pscip_irq_bh1 - called for interrupts on channel 1 of IP tasklets are a special function that may be scheduled to run, in software interrupt context, at a system-determined safe time.
They may be scheduled to run multiple times, but tasklet scheduling is not cumulative; the tasklet runs only once, even if it is requested repeatedly before it is launched. NOTE: tasklet function should return irqreturn_t but here this functions are initialized in "unconventional" way and they need to return void.....
Parameters:
data - data to be passed to the tasklet - anything cased to unsigned long - probably pointer
Definition at line 722 of file pscip.c.
References npscip_Dev::lock, npscip_Dev::queue, and queue_flag.
Referenced by init_pscip().
irqreturn_t pscip_irq_handler (int pciirq, void * dev_id, struct pt_regs * regs)
Interrupt hanlder.
Called when an interrupt occures.
It recognize whether the interrupt should be handled, checks errors and schedules appropraite tasklet function. Irq handler immediately reset pending interrupts to avoid CPU freezing
Parameters:
pciirq - interrupt number registered for this device,hardware-wise number of interrupt line
*dev_id - a sort of client data
*regs - holds a snapshot of the processors context before the processor entered interrupt code
Definition at line 761 of file pscip.c.
References pscip_stats_t::err_flag, IP_read_word(), IP_write_word(), npscip_Dev::irqflag, k_if_handle_irq(), pscip_stats_t::link_err_flag, pscip_stats_t::linkdown_cnt, npscip_Dev::pIP_IOspace, PLX9030_INTCSR_LINTI1_STAT, npscip_Dev::pPCIinterfaceReg, PSCIP_ERRCLEAR_MSK, PSCIP_ERROR_MSK, PSCIP_FPGA_HIGH, PSCIP_FPGA_LOW, PSCIP_FPGA_MID, PSCIP_IRQ_SERVED, PSCIP_LINKDOWN_MSK, PSCIP_RDWAVE_IDX, PSCIP_READ_IDX, PSCIP_REG_STAT, npscip_Dev::pscip_tsk, PSCIP_TXERR_MSK, PSCIP_WRHPRIO_IDX, PSCIP_WRITE_IDX, PSCIP_WRWAVE_IDX, npscip_Dev::stats, and pscip_stats_t::txerr_cnt.
Referenced by pscip_assign_irq().
static int pscip_open (struct inode * inode, struct file * filp) [static]
Function called when the node represeting driver is opened.
Does any initialization for later operations.
While creating first reference (first file/node open) interrupt on give IP are enabled
Parameters:
*inode - contains cdev structure, allows to get our device structure
*filp pointer to a file structure
Error code. Store error code in case of errro
Definition at line 200 of file pscip.c.
References npscip_Dev::irq, k_irq_enable(), pscip_assign_irq(), npscip_Dev::refcount, and npscip_Dev::sem.
static int pscip_procfs_register (void) [static]
Register proc filesystem entries.
It creates the appropriate directory in /proc/driver/ and fills it with nodes representing each IP It registers functions implemented for proc_fs interface
Definition at line 1058 of file pscip.c.
References npscip_Proc::count, module_name, proc_model_dir, pscip_dev_number, pscip_read_proc(), and pscip_write_proc().
Referenced by init_pscip_module().
static int pscip_read_proc (char * page, char ** start, off_t offset, int count, int * eof, void * data) [static]
Create a proc filesystem read entry.
Parameters:
*page - page pointer, buffer to which date is writen
**start - used by the function to say where the interesting data has been written
offset - the same as count
count -
*eof - points to an integer that must be set by the driver to signal that it has no more data to return
data -
Definition at line 879 of file pscip.c.
References npscip_Dev::carrier_number, pscip_fpga_t::channel, pscip_stats_t::cntrl_stat, npscip_Proc::count, pscip_fpga_t::high_data, id_pscip, npscip_Dev::IP_in_slot, npscip_Dev::IPnumber, k_pscip_rdfpgastat(), pscip_stats_t::linkdown_cnt, pscip_devices, PSCIP_DSP_MSK, PSCIP_INPUTBUF_MSK, PSCIP_LINKDOWN_MSK, PSCIP_MAX_CHAN, PSCIP_REMLOC_MSK, PSCIP_TXERR_MSK, pscip_stats_t::rx, npscip_Dev::sem, npscip_Dev::stats, pscip_stats_t::tx, pscip_stats_t::txerr_cnt, and ver.
Referenced by pscip_procfs_register().
static int pscip_release (struct inode * inode, struct file * filp) [static]
Function called when the node represeting driver is closed.
Invoked when the file structure is being released.
If the last reference is closed, interrupts are disabled on give IP represented by the file/node
Parameters:
*inode - contains cdev structure, allows to get our device structure
*filp pointer to a file structure
Definition at line 250 of file pscip.c.
References npscip_Dev::irq, k_irq_disable(), npscip_Dev::refcount, and npscip_Dev::sem.
static int pscip_write_proc (struct file * filp, const char * buffer, unsigned long count, void * data) [static]
creat a proc file system write entry
Parameters:
filep - file structure pointer
*buffer - data from the user
count -
*data -
Definition at line 964 of file pscip.c.
References pscip_t::address, pscip_t::chan, npscip_Proc::count, pscip_t::data, id_pscip, k_pscip_reset(), k_pscip_wrhiprio(), k_pscip_write(), k_pscip_wrwave(), pscip_devices, PSCIP_PROC_HPRIO, PSCIP_PROC_RESET, PSCIP_PROC_WRITE, PSCIP_PROC_WRWAVE, npscip_Dev::sem, pscip_t::stat, and val.
Referenced by pscip_procfs_register().
static void remove (struct pci_dev * pcidev) [static]
Function called when the device (Carrier) is removed from the PCI bus.
Does all the unregister/remove/free stuff in reverse order than probe.
Parameters:
*pcidev - structure representing PCI device
Definition at line 1393 of file pscip.c.
References npscip_Dev::pIP_IOspace, npscip_Dev::pIPinterfaceReg, npscip_Dev::pPCIinterfaceReg, pscip_devices, and npscip_Dev::pscip_number.
Variable Documentation
int hack_driver = 0 [static]
Module paramter - options for developer.
At the moment ot used
Definition at line 113 of file pscip.c.
const char* module_name = "pscip"
module name.
Definition at line 109 of file pscip.c.
Referenced by exit_pscip_module(), init_module(), probe(), and pscip_procfs_register().
struct proc_dir_entry* proc_model_dir [static]
Structure defining entry in proc file system.
Definition at line 186 of file pscip.c.
Referenced by exit_pscip_module(), and pscip_procfs_register().
int pscip_dev_number = 0 [static]
Module parameter - number of IPs.
Number of devices (IP modules) which will be in the computer, if not set, the DEFAULT number will be give, is limited by the MAX_DEV number
Definition at line 112 of file pscip.c.
Referenced by exit_pscip_module(), init_pscip_module(), probe(), and pscip_procfs_register().
struct pci_driver pscip_driver [static]
Initial value:
 {
 .name = "pscip",
 .id_table = ids,
 .probe = probe,
 .remove = remove,
}
Structure describing PCI device (IP).
Structure consists of a number of function callbacks and variables that describe the PCI driver to the PCI core
Definition at line 176 of file pscip.c.
Referenced by exit_pscip_module(), and init_pscip_module().
struct file_operations pscip_fops [static]
Initial value:
{
 .owner  =   THIS_MODULE,
 .ioctl  = pscip_ioctl,
 .open  = pscip_open,
 .release = pscip_release
}
File operation structure.
Associates the driver (major number) with device operations. The structure is a collection of function pointers. Each open file is associated with its own set of functions
Definition at line 164 of file pscip.c.
Referenced by probe().
int pscip_major [static]
Initial value:
 PSCIP_MAJOR_NUMBER
 module_param(pscip_dev_number, int, 0)
Global variable with major numer associated with the driver.
A default major number can be set in the header, if defalut value is 0 the major number is set dynamically unless user pass major number as a parameter
Definition at line 114 of file pscip.c.
Referenced by exit_pscip_module(), init_pscip_module(), and probe().
int pscip_minor = PSCIP_MINOR_NUMBER
Global variable with first minor numer associated with the driver.
Definition at line 106 of file pscip.c.
Referenced by exit_pscip_module(), init_pscip_module(), and probe().
pscip_Proc pscip_procdev [static]
Proc filesystem structure .
Definition at line 185 of file pscip.c.
int queue_flag = 0 [static]
Flag used in waitqueue mechanism.
This is a provisional solution, probablyl needs better implementation
Definition at line 91 of file pscip.c.
Referenced by k_pscip_rdwave(), k_pscip_read(), k_pscip_wrhiprio(), k_pscip_write(), k_pscip_wrwave(), pscip_irq_bh0(), and pscip_irq_bh1().
char ver[10] = "1.0" [static]
Module/driver version.
Definition at line 108 of file pscip.c.
Referenced by pscip_read_proc().