#!/bin/sh
module="pscip"
device="pscip"

# invoke rmmod with all arguments we got
/sbin/rmmod $module $* || exit 1

# Remove stale nodes

rm -f /dev/${device} /dev/${device}[0-3] 

#dispaly something :)
tail /var/log/messages



